### ISSUE TITLE
zip() can't be used as input

### ISSUE THREAD

**Issue by haizaar** [josh-paul/dotted_dict#1]
Good day.

```python
l = ["a", "b", "c"]
print(dict(zip(l, l)))  # -> {'a': 'a', 'b': 'b', 'c': 'c'}
```
While
```python
from dotted_dict import DottedDict
l = ["a", "b", "c"]
print(DottedDict(zip(l, l)))  # -> DottedDict({})
```
I.e. empty dictionary. Bug?

P.S. Thank you for writing this library - it got tired implementing it myself in my new projects, but lazy enough to publish my own version :)

**Comment by josh-paul** [comment]
This is an issue due to the change in zip() in python 3 returning an iterator.  Testing a potential fix.

**Comment by josh-paul** [comment]
@haizaar: Can you verify the python version you are encountering this?

**Comment by haizaar** [comment]
Verified with Python 3.7.1 over dotted-dict-1.1.1. Thank you very much!
